parameters:
#    skonsoft_lftp_deployement.example.class: Skonsoft\Bundle\LftpDeployementBundle\Example

services:
#    skonsoft_lftp_deployement.example:
#        class: %skonsoft_lftp_deployement.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
